server:
  port: 8000

spring:
  application:
    name: uc-control
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/admin_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false #解决tinyint(1) 在java中被转化为boolean
    username: root
    password: 123456
    druid:
      validation-query: SELECT 1

  # redis properties
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        min-idle: 50
        max-active: 20
        max-wait: 500000

mybatis-plus:
  type-aliases-package: com.zhuyz.cloud.entity  # 所有Entity别名类所在包
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    #驼峰下划线转换
    db-column-underline: true



#pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka